"""empty message

Revision ID: 10439de3184d
Revises: b0be550404f3
Create Date: 2020-02-04 14:56:54.754080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10439de3184d'
down_revision = 'b0be550404f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
